#!/usr/bin/bash

cp -t ./ "/media/Music/Audio/Misc Songs/Splash 1.mp3"
cp -t ./ "/media/Music/Audio/Aerosmith/Dream On.mp3"
cp -t ./ "/media/Music/Audio/Aerosmith/Don't want 2 miss a thing.mp3"
cp -t ./ "/media/Music/Audio/Aerosmith/Big Ones/05 - Dude (Looks like a lady).MP3"
cp -t ./ "/media/Music/Audio/Aerosmith/Big Ones/06 - Janie's Got a Gun.mp3"
cp -t ./ "/media/Music/Audio/Aerosmith/Big Ones/08 - Amazing.mp3"
cp -t ./ "/media/Music/Audio/Aerosmith/Big Ones/09 - Blind Man.mp3"
cp -t ./ "/media/Music/Audio/Aerosmith/Big Ones/12 - Crazy.mp3"
cp -t ./ "/media/Music/Audio/Aerosmith/Big Ones/15 - Livin on the Edge.mp3"
cp -t ./ "/media/Music/Audio/Aerosmith/Kings And Queens.mp3"
cp -t ./ "/media/Music/Audio/Aerosmith/Seasons Of Wither.mp3"
cp -t ./ "/media/Music/Audio/Aerosmith/Just Push Play/12 Avant Garden.mp3"
cp -t ./ "/media/Music/Audio/Aerosmith/Nine Lives/07 - Ain't That a Bitch.mp3"
cp -t ./ "/media/Music/Audio/Aerosmith/Nine Lives/10 - Kiss Your Past Good-bye.mp3"
cp -t ./ "/media/Music/Audio/Aerosmith/Nine Lives/11 - Pink.mp3"
cp -t ./ "/media/Music/Audio/Punk/Against Me!/New Wave/01 - new wave.mp3"
cp -t ./ "/media/Music/Audio/Punk/Against Me!/New Wave/06 - borne on the fm waves.mp3"
cp -t ./ "/media/Music/Audio/Punk/Against Me!/Reinventing Axl Rose/09- Baby, I'm an Anarchist!.mp3"
cp -t ./ "/media/Music/Audio/Punk/Against Me!/White Crosses(2010)/01-White Crosses.mp3"
cp -t ./ "/media/Music/Audio/Punk/Against Me!/White Crosses(2010)/02-I Was A Teenage Anarchist.mp3"
cp -t ./ "/media/Music/Audio/Punk/Against Me!/White Crosses(2010)/07-Ache With Me.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Black Gives Way To Blue/04 - Your Decision.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Misc/Rooster.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./Alison Krauss/2007 - A Hundred Miles Or More/01 - You're Just A Country Boy.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./Alison Krauss/2007 - A Hundred Miles Or More/02 - Simple Love.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./Alison Krauss/2007 - A Hundred Miles Or More/03 - Jacob's Dream.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./Alison Krauss/2007 - A Hundred Miles Or More/04 - Away Down The River.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./Alison Krauss/2007 - A Hundred Miles Or More/11 - Whiskey Lullaby (With Brad Paisley).mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./Alison Krauss/2007 - A Hundred Miles Or More/14 - Get Me Through December.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./Alison Krauss/1999 - Forget About It/02 - Forget About It.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./Alison Krauss/1999 - Forget About It/03 - It Wouldn't Have Made Any Difference.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./Alison Krauss/1997 - So Long, So Wrong/01 - So Long, So Wrong.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./Alison Krauss/2011 - Paper Airplane/07 - On the Outside Looking In.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./Alison Krauss/2002 - Live/103 The Lucky One.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./Alison Krauss/2002 - Live/105 Bright Sunny South.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./The Country Way Digital Sampler/04  Shanghai Cigarettes.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./The Country Way Digital Sampler/07  From a Table Away.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./The Country Way Digital Sampler/08  The Rain.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./The Country Way Digital Sampler/10  How Good You Are.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./The Country Way Digital Sampler/11  Barton Hollow.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./The Country Way Digital Sampler/16  1000 Faces.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./The Country Way Digital Sampler/18  Couyon Crazy.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./The Country Way Digital Sampler/20  Gone Like That.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./The Country Way Digital Sampler/25  Catfish And Color TVs.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./The Country Way Digital Sampler/29  Still Down Here.mp3"
cp -t ./ "/media/Music/Audio/Tom Delonge/Angels & Airwaves/The War.mp3"
cp -t ./ "/media/Music/Audio/Tom Delonge/Angels & Airwaves/It Hurts.mp3"
cp -t ./ "/media/Music/Audio/Tom Delonge/Angels & Airwaves/Start The Machine.mp3"
cp -t ./ "/media/Music/Audio/Arctic Monkeys/Suck It And See (2011)/01-She's Thunderstorms.mp3"
cp -t ./ "/media/Music/Audio/Arctic Monkeys/Suck It And See (2011)/11-Suck It And See.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Diamonds Unlocked/05 - Love Gun (Kiss).mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Diamonds Unlocked/09 - In The Air Tonight (Phil Collins).mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Diamonds Unlocked/10 - Like a child again (The Mission).mp3"
cp -t ./ "/media/Music/Audio/Eminem/Bad Meets Evil - Hell The Sequel (2011)/09 - Loud Noiss ft. Slaughterhouse.mp3"
cp -t ./ "/media/Music/Audio/Story of the Year/Big Blue Monkey/In Her Bedroom.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/Idolize Yourself/01 Dancing With Myself.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/Idolize Yourself/03 White Wedding (Part 1).mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/Idolize Yourself/04 Rebell Yell.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/Idolize Yourself/13 LA Woman.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Zakk Wylde/Black Label Society/Bridge To Cross.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Zakk Wylde/Black Label Society/Snowblind.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Zakk Wylde/Black Label Society/Whiter Shade Of Pale.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Zakk Wylde/Black Label Society/In This River.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Zakk Wylde/Black Label Society/Blood Is Thicker Than Water.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Zakk Wylde/Black Label Society/Stillborn Feat Ozzy Osbourne.mp3"
cp -t ./ "/media/Music/Audio/00NewStuffs/Black Label Society/The Song Remains Not The Same/04-black_label_society-darkest_days.mp3"
cp -t ./ "/media/Music/Audio/00NewStuffs/Black Label Society/The Song Remains Not The Same/06-black_label_society-helpless.mp3"
cp -t ./ "/media/Music/Audio/00NewStuffs/Black Label Society/The Song Remains Not The Same/07-black_label_society-bridge_over_troubled_water.mp3"
cp -t ./ "/media/Music/Audio/00NewStuffs/Black Label Society/The Song Remains Not The Same/09-black_label_society-darkest_days_(john_rich_album_version).mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Ozzy/It's Alright.mp3"
cp -t ./ "/media/Music/Audio/Tom Delonge/Blink 182/Blink-182/03-I Miss You.mp3"
cp -t ./ "/media/Music/Audio/Tom Delonge/Blink 182/Enema Of The State/07-Adam's Song.mp3"
cp -t ./ "/media/Music/Audio/Tom Delonge/Blink 182/Neighborhoods (2011)/01 - Ghost on the Dance Floor.mp3"
cp -t ./ "/media/Music/Audio/Tom Delonge/Blink 182/Neighborhoods (2011)/08 - Wishing Well.mp3"
cp -t ./ "/media/Music/Audio/Tom Delonge/Blink 182/Take Off Your Pants And Jacket/07-Stay Together For The Kids.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./Bob Dylan/Blowing In The Wind.mp3"
cp -t ./ "/media/Music/Audio/Misc Artists/Bon Jovi/Cross Road - The Best of Bon Jovi/04 Always.mp3"
cp -t ./ "/media/Music/Audio/Misc Artists/Bon Jovi/Cross Road - The Best of Bon Jovi/05 Wanted Dead or Alive.mp3"
cp -t ./ "/media/Music/Audio/Misc Artists/Bon Jovi/Cross Road - The Best of Bon Jovi/07 You Give Love a Bad Name.mp3"
cp -t ./ "/media/Music/Audio/00NewStuffs/Indro/Boston Greatest Hits/A Man I'll Never Be.mp3"
cp -t ./ "/media/Music/Audio/Bowling for Soup/A Hangover You Don't Deserve/03 1985 1986.mp3"
cp -t ./ "/media/Music/Audio/Bowling for Soup/The Great Burrito Extortion Case/02 - High School Never Ends.mp3"
cp -t ./ "/media/Music/Audio/Bowling for Soup/The Great Burrito Extortion Case/03 - Val Kilmer.mp3"
cp -t ./ "/media/Music/Audio/Bowling for Soup/The Great Burrito Extortion Case/05 - Why Dont I Miss You.mp3"
cp -t ./ "/media/Music/Audio/Bowling for Soup/The Great Burrito Extortion Case/09 - Much More Beautiful Person.mp3"
cp -t ./ "/media/Music/Audio/Post Led Zep/Box Of Frogs_Strange Land/102 - Harder.mp3"
cp -t ./ "/media/Music/Audio/Post Led Zep/Box Of Frogs_Strange Land/104 - Love Inside You.mp3"
cp -t ./ "/media/Music/Audio/Post Led Zep/Box Of Frogs_Strange Land/106 - Two Steps Ahead.mp3"
cp -t ./ "/media/Music/Audio/Post Led Zep/Box Of Frogs_Strange Land/107 - Into The Dark.mp3"
cp -t ./ "/media/Music/Audio/Post Led Zep/Box Of Frogs_Strange Land/108 - Just A Boy Again.mp3"
cp -t ./ "/media/Music/Audio/Post Led Zep/Box Of Frogs_Strange Land/202 - You Mix Me Up.mp3"
cp -t ./ "/media/Music/Audio/Post Led Zep/Box Of Frogs_Strange Land/203 - Average.mp3"
cp -t ./ "/media/Music/Audio/Post Led Zep/Box Of Frogs_Strange Land/208 - Strange Land.mp3"
cp -t ./ "/media/Music/Audio/Tom Delonge/Boxcar Racer/03 Watch the world.mp3"
cp -t ./ "/media/Music/Audio/Tom Delonge/Boxcar Racer/06 And I.mp3"
cp -t ./ "/media/Music/Audio/Tom Delonge/Boxcar Racer/07 Letters to god.mp3"
cp -t ./ "/media/Music/Audio/Tom Delonge/Boxcar Racer/10 There is.mp3"
cp -t ./ "/media/Music/Audio/Tom Delonge/Boxcar Racer/11 The end with you.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/Everything I Do) I Do It For You.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Mustang Sally.mp3"
cp -t ./ "/media/Music/Audio/Crap/Bullet For My Valentine/The Poison/07 - All These Things I Hate (Revolve Around Me).mp3"
cp -t ./ "/media/Music/Audio/00NewStuffs/Indro/Bush/Everything Zen.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./On The Road Again.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Chelsea Wolfe - 2013 - Pain is Beauty/10 They'll Clap When You're Gone.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Chickenfoot/08 - My Kinda Girl.mp3"
cp -t ./ "/media/Music/Audio/Children Of Bodom/[2005] Are You Dead Yet/01. Living Dead Beat.mp3"
cp -t ./ "/media/Music/Audio/Children Of Bodom/[2005] Are You Dead Yet/05. In Your Face.mp3"
cp -t ./ "/media/Music/Audio/Children Of Bodom/Tie My Rope.mp3"
cp -t ./ "/media/Music/Audio/Children Of Bodom/[2003] Hate Crew Deathroll/01. Needled 24-7.mp3"
cp -t ./ "/media/Music/Audio/Children Of Bodom/[2003] Hate Crew Deathroll/02. Sixpounder.mp3"
cp -t ./ "/media/Music/Audio/Children Of Bodom/[2003] Hate Crew Deathroll/06. Triple Corpse Hammerblow.mp3"
cp -t ./ "/media/Music/Audio/Children Of Bodom/[2011] Relentless Reckless Forever/07. Cry Of The Nihilist.mp3"
cp -t ./ "/media/Music/Audio/Children Of Bodom/[2009] Skeletons In The Closet/01-Looking At My Back Door.mp3"
cp -t ./ "/media/Music/Audio/Children Of Bodom/[2009] Skeletons In The Closet/03-Somebody Put Something.mp3"
cp -t ./ "/media/Music/Audio/Children Of Bodom/[2009] Skeletons In The Closet/07-She Is Beautiful.mp3"
cp -t ./ "/media/Music/Audio/Children Of Bodom/[2009] Skeletons In The Closet/08-Just Dropped In.mp3"
cp -t ./ "/media/Music/Audio/Children Of Bodom/[2009] Skeletons In The Closet/12-Rebel Yell.mp3"
cp -t ./ "/media/Music/Audio/Children Of Bodom/[2009] Skeletons In The Closet/15-Talk Dirty To Me.mp3"
cp -t ./ "/media/Music/Audio/Children Of Bodom/[2009] Skeletons In The Closet/17-Ooops! I Did It Again.mp3"
cp -t ./ "/media/Music/Audio/Concrete Blonde/Bloodletting/09 Joey.mp3"
cp -t ./ "/media/Music/Audio/Concrete Blonde/Concrete Blonde/03 Dance Along The Edge.mp3"
cp -t ./ "/media/Music/Audio/Concrete Blonde/Concrete Blonde/05 Song For Kim (She Said).mp3"
cp -t ./ "/media/Music/Audio/Concrete Blonde/Scene Of A Perfect Crime.mp3"
cp -t ./ "/media/Music/Audio/Concrete Blonde/Cold Part Of Town.mp3"
cp -t ./ "/media/Music/Audio/Post Led Zep/Take Me for a Little While.mp3"
cp -t ./ "/media/Music/Audio/Post Led Zep/Over Now.mp3"
cp -t ./ "/media/Music/Audio/Classics/Cream/Fresh Cream/02 - N.S.U..mp3"
cp -t ./ "/media/Music/Audio/Classics/Cream/Fresh Cream/06 - Spoonful.mp3"
cp -t ./ "/media/Music/Audio/Classics/Cream/Fresh Cream/12 - The Coffee Song.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/riders on the storm.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Creedence Clearwater Revival/Bayou Country/1 - Born On The Bayou.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Creedence Clearwater Revival/Bayou Country/6 - Proud Mary.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Creedence Clearwater Revival/The Very Best Of Creedence Clearwater Revival/Lookin' Out My Back Door.mp3"
cp -t ./ "/media/Music/Audio/Classics/Crosby, Stills, Nash & Young/04 Helpless.mp3"
cp -t ./ "/media/Music/Audio/Dashboard Confessional/[2003] A Mark, A Mission, A Brand, A Scar/01 Hands down.mp3"
cp -t ./ "/media/Music/Audio/Dashboard Confessional/[2003] A Mark, A Mission, A Brand, A Scar/07 Am I Missing.mp3"
cp -t ./ "/media/Music/Audio/Dashboard Confessional/[2009] Alter the Ending/Alter the Ending/06 Alter the Ending.mp3"
cp -t ./ "/media/Music/Audio/Dashboard Confessional/[2002] MTV Unplugged Live/07 The Places You Have Come to Fear the Most.mp3"
cp -t ./ "/media/Music/Audio/Dashboard Confessional/[2002] MTV Unplugged Live/15 Hands Down.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/Late Night Radio.mp3"
cp -t ./ "/media/Music/Audio/Punk/Demolition23/02 - Hammersmith Palais.mp3"
cp -t ./ "/media/Music/Audio/Classics/Derek And The Dominos - Layla and other assorted love songs - 1970/03 Keep On Growing.mp3"
cp -t ./ "/media/Music/Audio/Dire Straits/Once upon a Time in the West.mp3"
cp -t ./ "/media/Music/Audio/Dire Straits/Portobello Belle.mp3"
cp -t ./ "/media/Music/Audio/Dire Straits/Sultans of Swing_ The Very Best of Dire Straits/01 - Sultans of Swing.mp3"
cp -t ./ "/media/Music/Audio/Dire Straits/Sultans of Swing_ The Very Best of Dire Straits/10 - Brothers in Arms.mp3"
cp -t ./ "/media/Music/Audio/Dire Straits/Portobello Belle - Live.mp3"
cp -t ./ "/media/Music/Audio/Disturbed/Asylum (2010)/13 - Ishfwilf.mp3"
cp -t ./ "/media/Music/Audio/Disturbed/Believe/03-Awaken.mp3"
cp -t ./ "/media/Music/Audio/Disturbed/Indestructable/01-Indestructible.mp3"
cp -t ./ "/media/Music/Audio/Disturbed/Indestructable/04-The Night.mp3"
cp -t ./ "/media/Music/Audio/Disturbed/Ten Thousand Fists/01 Ten Thousand Fists.mp3"
cp -t ./ "/media/Music/Audio/Disturbed/The Sickness/02-The Game.mp3"
cp -t ./ "/media/Music/Audio/Disturbed/The Sickness/03-Stupify.mp3"
cp -t ./ "/media/Music/Audio/Disturbed/The Sickness/04-Down With The Sickness.mp3"
cp -t ./ "/media/Music/Audio/Disturbed/The Sickness/05-Violence Fetish.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/American Pie (Original Version.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Dream Theater/As I Am.mp3"
cp -t ./ "/media/Music/Audio/Misc Artists/Elton John/Levon.mp3"
cp -t ./ "/media/Music/Audio/Misc Artists/Elton John/Tiny Dancer.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/Rocket Man (I Think It's Going.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/I Guess That's Why They Call It The Blues.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Faith No More/Angel Dust/10 - A Small Victory.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Faith No More/Angel Dust/14 - Easy.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Faith No More/The Real Thing/03 - Falling To Pieces.mp3"
cp -t ./ "/media/Music/Audio/Crap/Fall Out Boys/Infinity On High/01-Thriller.mp3"
cp -t ./ "/media/Music/Audio/Crap/Fall Out Boys/Infinity On High/05-Hum Hallelujah.mp3"
cp -t ./ "/media/Music/Audio/Crap/Fall Out Boys/Infinity On High/07-Thnks Fr Th Mmrs.mp3"
cp -t ./ "/media/Music/Audio/Crap/Fall Out Boys/Suga Were Goin Down.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/Come Back Around.mp3"
cp -t ./ "/media/Music/Audio/Classics/Fleetwood Mac/1975 - Fleetwood Mac/02 Warm Ways.mp3"
cp -t ./ "/media/Music/Audio/Classics/Fleetwood Mac/1977 - Rumours/07 The Chain.mp3"
cp -t ./ "/media/Music/Audio/Green Day/Foxboro Hot Tubs/04 Red Tide.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/G3-LiveConcert/11 - My Guitar Wants to Kill Your Mama.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Godsmack/Serenity.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Godsmack/I Stand Alone.mp3"
cp -t ./ "/media/Music/Audio/Punk/Pop_Alt_etc/Good Charlotte/THE RIVER.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Gov't Mule - Temporary Saint.mp3"
cp -t ./ "/media/Music/Audio/Green Day/1039 Smoothed Out Slappy Hours/03-I Was There.mp3"
cp -t ./ "/media/Music/Audio/Green Day/1039 Smoothed Out Slappy Hours/09-Rest.mp3"
cp -t ./ "/media/Music/Audio/Green Day/1039 Smoothed Out Slappy Hours/19-I Want to Be Alone.mp3"
cp -t ./ "/media/Music/Audio/Green Day/21st Century Breakdown/02 - 21st Century Breakdown.mp3"
cp -t ./ "/media/Music/Audio/Green Day/21st Century Breakdown/05 - Before the Lobotomy.mp3"
cp -t ./ "/media/Music/Audio/Green Day/21st Century Breakdown/07 - Last Night on Earth.mp3"
cp -t ./ "/media/Music/Audio/Green Day/21st Century Breakdown/08 - East Jesus Nowhere.mp3"
cp -t ./ "/media/Music/Audio/Green Day/21st Century Breakdown/09 - Peacemaker.mp3"
cp -t ./ "/media/Music/Audio/Green Day/21st Century Breakdown/10 - Last of the American Girls.mp3"
cp -t ./ "/media/Music/Audio/Green Day/21st Century Breakdown/13 - Restless Heart Syndrome.mp3"
cp -t ./ "/media/Music/Audio/Green Day/21st Century Breakdown/14 - Horseshoes and Handgrenades.mp3"
cp -t ./ "/media/Music/Audio/Green Day/21st Century Breakdown/16 - 21 Guns.mp3"
cp -t ./ "/media/Music/Audio/Green Day/21st Century Breakdown/18 - See the Light.mp3"
cp -t ./ "/media/Music/Audio/Green Day/American Idiot/01 - American Idiot.mp3"
cp -t ./ "/media/Music/Audio/Green Day/American Idiot/02 - Jesus Of Suburbia.mp3"
cp -t ./ "/media/Music/Audio/Green Day/American Idiot/03 - Holiday.mp3"
cp -t ./ "/media/Music/Audio/Green Day/American Idiot/04 - Boulevard Of Broken Dreams.mp3"
cp -t ./ "/media/Music/Audio/Green Day/American Idiot/05 - Are We The Waiting.mp3"
cp -t ./ "/media/Music/Audio/Green Day/American Idiot/06 - St Jimmi.mp3"
cp -t ./ "/media/Music/Audio/Green Day/American Idiot/07 - Give Me Novocaine.mp3"
cp -t ./ "/media/Music/Audio/Green Day/American Idiot/09 - Extraordinary Girl.mp3"
cp -t ./ "/media/Music/Audio/Green Day/American Idiot/11 - Wake Me Up When September Ends.mp3"
cp -t ./ "/media/Music/Audio/Green Day/American Idiot/12 - Homecoming.mp3"
cp -t ./ "/media/Music/Audio/Green Day/Dookie/07 Basket Case.mp3"
cp -t ./ "/media/Music/Audio/Green Day/International Superhits/21-Macy's Day Parade.mp3"
cp -t ./ "/media/Music/Audio/Green Day/Kerplunk/03-Welcome To Paradise (Kerplunk Version).mp3"
cp -t ./ "/media/Music/Audio/Green Day/green day - time of your life (acoustic).mp3"
cp -t ./ "/media/Music/Audio/Green Day/Nimrod/04-Redundant.mp3"
cp -t ./ "/media/Music/Audio/Green Day/Nimrod/17-Good Riddance (Time Of Your Li.mp3"
cp -t ./ "/media/Music/Audio/Guns N' Roses/Appetite For Destruction/01 - Welcome To The Jungle.mp3"
cp -t ./ "/media/Music/Audio/Guns N' Roses/Appetite For Destruction/09 - Sweet Child O' Mine.mp3"
cp -t ./ "/media/Music/Audio/Guns N' Roses/Appetite For Destruction/12 - Rocket Queen.mp3"
cp -t ./ "/media/Music/Audio/Guns N' Roses/Live Era 87 - 93/10 - Estranged.wma"
cp -t ./ "/media/Music/Audio/Guns N' Roses/The Spaghetti Incident/06 - Ain't It Fun.MP3"
cp -t ./ "/media/Music/Audio/Guns N' Roses/Use Your Illusion I/04 - Don't Cry [Original Version].MP3"
cp -t ./ "/media/Music/Audio/Guns N' Roses/Use Your Illusion I/07 - Bad Obsession.MP3"
cp -t ./ "/media/Music/Audio/Guns N' Roses/Use Your Illusion I/10 - November Rain.MP3"
cp -t ./ "/media/Music/Audio/Guns N' Roses/Dont Cry (Alt. Lyrics).mp3"
cp -t ./ "/media/Music/Audio/Guns N' Roses/Use Your Illusion II/02 - 14 Years.MP3"
cp -t ./ "/media/Music/Audio/Guns N' Roses/Use Your Illusion II/05 - Knocking On Heavens Doors.mp3"
cp -t ./ "/media/Music/Audio/Guns N' Roses/Use Your Illusion II/07 - Breakdown.MP3"
cp -t ./ "/media/Music/Audio/Guns N' Roses/Use Your Illusion II/10 - So Fine.MP3"
cp -t ./ "/media/Music/Audio/Guns N' Roses/Use Your Illusion II/11 - Estranged.MP3"
cp -t ./ "/media/Music/Audio/Emo/Niki FM.mp3"
cp -t ./ "/media/Music/Audio/00NewStuffs/Indro/Heart/01 Crazy on You.mp3"
cp -t ./ "/media/Music/Audio/00NewStuffs/Indro/Heart/04 Barracuda.mp3"
cp -t ./ "/media/Music/Audio/00NewStuffs/Indro/Heart/10 Dog and Butterfly.mp3"
cp -t ./ "/media/Music/Audio/00NewStuffs/Indro/Heart/18 Allies.mp3"
cp -t ./ "/media/Music/Audio/00NewStuffs/Indro/Heart/07 Who Will You Run To.mp3"
cp -t ./ "/media/Music/Audio/00NewStuffs/Indro/Heart/08 There's the Girl.mp3"
cp -t ./ "/media/Music/Audio/Misc Artists/Iggy Pop/103  I Wanna Be Your D.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/Afterglow.mp3"
cp -t ./ "/media/Music/Audio/Jack White/Blunderbuss 2012/10 Hip (Eponymous) Poor Boy.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Janis Joplin/Cry Baby (The Ultimate Collection) [2009]/109-Kozmic Blues.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Janis Joplin/Cry Baby (The Ultimate Collection) [2009]/118-Ball And Chain (live).mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Janis Joplin/Cry Baby (The Ultimate Collection) [2009]/202-Cry Baby.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Janis Joplin/Cry Baby (The Ultimate Collection) [2009]/213-Kozmic Blues (live).mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Janis Joplin/Cry Baby (The Ultimate Collection) [2009]/218-Maybe (live).mp3"
cp -t ./ "/media/Music/Audio/Misc Artists/Jason Mraz/MR. A-Z/02 Wordplay.mp3"
cp -t ./ "/media/Music/Audio/Jefferson/Jefferson Airplane/1967 - After Bathing At Baxter's/07 - Rejoice.mp3"
cp -t ./ "/media/Music/Audio/Jefferson/Jefferson Airplane/1967 - After Bathing At Baxter's/08 - Watch Her Ride.mp3"
cp -t ./ "/media/Music/Audio/Jefferson/Jefferson Airplane/1967 - After Bathing At Baxter's/10 - Two Heads.mp3"
cp -t ./ "/media/Music/Audio/Jefferson/Jefferson Airplane/1967 - After Bathing At Baxter's/11 - Won't You Try.mp3"
cp -t ./ "/media/Music/Audio/Jefferson/Jefferson Airplane/1967 - After Bathing At Baxter's/12 - Saturday Afternoon.mp3"
cp -t ./ "/media/Music/Audio/Jefferson/Jefferson Airplane/1968 - Crown Of Creation/01 - Lather.MP3"
cp -t ./ "/media/Music/Audio/Jefferson/Jefferson Airplane/1968 - Crown Of Creation/02 - In Time.MP3"
cp -t ./ "/media/Music/Audio/Jefferson/Jefferson Airplane/1968 - Crown Of Creation/03 - Triad.MP3"
cp -t ./ "/media/Music/Audio/Jefferson/Jefferson Airplane/1968 - Crown Of Creation/08 - Crown Of Creation.MP3"
cp -t ./ "/media/Music/Audio/Jefferson/Jefferson Airplane/1968 - Crown Of Creation/09 - Ice Cream Phoenix.MP3"
cp -t ./ "/media/Music/Audio/Jefferson/Jefferson Airplane/1968 - Crown Of Creation/10 - Greasy Heart.MP3"
cp -t ./ "/media/Music/Audio/Jefferson/Jefferson Airplane/1968 - Crown Of Creation/11 - The House At Pooneil Corners.MP3"
cp -t ./ "/media/Music/Audio/Jefferson/Jefferson Airplane/1967 - Surrealistic Pillow/02 - Somebody to Love.mp3"
cp -t ./ "/media/Music/Audio/Jefferson/Jefferson Airplane/1967 - Surrealistic Pillow/04 - Today.mp3"
cp -t ./ "/media/Music/Audio/Jefferson/Jefferson Airplane/1967 - Surrealistic Pillow/10 - White Rabbit.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/Get Born/02.Are You Gotta Be My Girl.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/Get Born/04.Look What You've Done.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/Get Born/06.Move On.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/Get Born/07.Radio Song.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/Get Born/13.Timothy.mp3"
cp -t ./ "/media/Music/Audio/Classics/Jethro Tull/Aqualung/04 - Mother Goose.mp3"
cp -t ./ "/media/Music/Audio/Classics/Jethro Tull/Aqualung/07 - My God.mp3"
cp -t ./ "/media/Music/Audio/Classics/Jethro Tull/Aqualung/11 - Wind-Up.mp3"
cp -t ./ "/media/Music/Audio/Classics/Jethro Tull/Broadsword.mp3"
cp -t ./ "/media/Music/Audio/Classics/Jethro Tull/The Best Of Acoustic/04 - Mother Goose.mp3"
cp -t ./ "/media/Music/Audio/Classics/Jethro Tull/Song For Jeffrey.mp3"
cp -t ./ "/media/Music/Audio/Post Led Zep/Walking Into Clarksdale/10 When I Was A Child.mp3"
cp -t ./ "/media/Music/Audio/Misc Artists/Bon Jovi/Cross Road - The Best of Bon Jovi/09 Blaze of Glory.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Judas Priest/Breaking The Law.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Judas Priest/You've Got Another Thing Comin'.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Kiss/04 - Sure Know Something.MP3"
cp -t ./ "/media/Music/Audio/Metal stuff/Kiss/05 - Love Gun.MP3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./Lady Antebellum/2008 Lady Antebellum/01 Love Don't Live Here.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./Lady Antebellum/2008 Lady Antebellum/02 Lookin' For A Good Time.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./Lady Antebellum/2010 Need You Now/01 Need You Now.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./Lady Antebellum/2011 Own The Night/03 - Dancin' Away With My Heart.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./Lady Antebellum/2011 Own The Night/06 - Cold As Stone.mp3"
cp -t ./ "/media/Music/Audio/00NewStuffs/Little River Band - The Net/02 We Two.mp3"
cp -t ./ "/media/Music/Audio/00NewStuffs/Indro/The Blue Mask/04 Gun.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Lynyrd Skynyrd/Things goin' on.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Lynyrd Skynyrd/Mississippi Kid.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Lynyrd Skynyrd/Skynyrd's First and Last/2-Preacher's Daughter.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Lynyrd Skynyrd/The Essential Lynyrd Skynyrd (1998)/101 - Sweet Home Alabama.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Lynyrd Skynyrd/The Essential Lynyrd Skynyrd (1998)/106 - Simple Man.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Lynyrd Skynyrd/The Essential Lynyrd Skynyrd (1998)/108 - The Ballad Of Curtis Loew.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Lynyrd Skynyrd/The Essential Lynyrd Skynyrd (1998)/111 - Comin' Home (Original Version).mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Lynyrd Skynyrd/The Essential Lynyrd Skynyrd (1998)/113 - Free Bird.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Lynyrd Skynyrd/The Essential Lynyrd Skynyrd (1998)/203 - Tuesday's Gone.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Lynyrd Skynyrd/The Essential Lynyrd Skynyrd (1998)/205 - I Know A Little.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Lynyrd Skynyrd/The Essential Lynyrd Skynyrd (1998)/212 - Free Bird (Live).mp3"
cp -t ./ "/media/Music/Audio/Megadeth/Endgame/03 - 44 Minutes.mp3"
cp -t ./ "/media/Music/Audio/Megadeth/Peace Sells_But Who's Buying/02 - The Conjuring.mp3"
cp -t ./ "/media/Music/Audio/Megadeth/I'll be there.mp3"
cp -t ./ "/media/Music/Audio/Megadeth/Seven.mp3"
cp -t ./ "/media/Music/Audio/Megadeth/Rust In Peace/01 - Holy Wars_The Punishment Due.mp3"
cp -t ./ "/media/Music/Audio/Megadeth/The World Needs A Hero/Coming Home.mp3"
cp -t ./ "/media/Music/Audio/Megadeth/United Abominations/09 - Amerikhastan.mp3"
cp -t ./ "/media/Music/Audio/Megadeth/Youthanasia/04 - A Tout Le Monde.mp3"
cp -t ./ "/media/Music/Audio/Misc Artists/Michael Jackson/15 Billie Jean.mp3"
cp -t ./ "/media/Music/Audio/Misc Artists/Michael Jackson/06 Smooth Criminal.mp3"
cp -t ./ "/media/Music/Audio/Misc Artists/Michael Jackson/17 Wanna Be Startin Something.mp3"
cp -t ./ "/media/Music/Audio/Misc Artists/Michael Jackson/04 Dirty Diana.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Molly Hatchet - Greatest Hits/10 Fall of the Peacemakers.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/The Good, The Bad And The Ugly/10 The Ecstacy Of Gold.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Motley Crue - Greatest Hits/04 - Kickstart My Heart.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Motley Crue - Greatest Hits/06 - Glitter.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Motley Crue - Greatest Hits/07 - Dr. Feelgood.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Motley Crue - Greatest Hits/08 - Same 01'situations.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Motley Crue - Greatest Hits/09 - Home Sweet Home.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Motley Crue - Greatest Hits/11 - Don't Go Away Mad.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Motley Crue - Greatest Hits/15 - Too Fast for Love.mp3"
cp -t ./ "/media/Music/Audio/My Chemical Romance/Danger Days (2010)/06 The Only Hope For Me Is You.mp3"
cp -t ./ "/media/Music/Audio/My Chemical Romance/I Brought You My Bullets, You Brought Me Your Love/03 - Vampires Will Never Hurt You.mp3"
cp -t ./ "/media/Music/Audio/My Chemical Romance/I Brought You My Bullets, You Brought Me Your Love/08 - Early Sunsets Over Monroeville.mp3"
cp -t ./ "/media/Music/Audio/My Chemical Romance/I Brought You My Bullets, You Brought Me Your Love/11 - Demolition Lovers.mp3"
cp -t ./ "/media/Music/Audio/My Chemical Romance/The Black Parade/01 - The End..mp3"
cp -t ./ "/media/Music/Audio/My Chemical Romance/The Black Parade/03 - This Is How I Disappear.mp3"
cp -t ./ "/media/Music/Audio/My Chemical Romance/The Black Parade/05 - Welcome To The Black Parade.mp3"
cp -t ./ "/media/Music/Audio/My Chemical Romance/The Black Parade/06 - I Don't Love You.mp3"
cp -t ./ "/media/Music/Audio/My Chemical Romance/The Black Parade/09 - Mama.mp3"
cp -t ./ "/media/Music/Audio/My Chemical Romance/The Black Parade/10 - Sleep.mp3"
cp -t ./ "/media/Music/Audio/My Chemical Romance/The Black Parade/11 - Teenagers.mp3"
cp -t ./ "/media/Music/Audio/My Chemical Romance/The Black Parade/12 - Disenchanted.mp3"
cp -t ./ "/media/Music/Audio/My Chemical Romance/The Black Parade/13 - Famous Last Words.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Nazareth/40 Very Best/06 Expect No Mercy.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Nazareth/Star.mp3"
cp -t ./ "/media/Music/Audio/Classics/Neil Young/Old Man.mp3"
cp -t ./ "/media/Music/Audio/Classics/Neil Young/Everybody Knows This Is Nowhere [Crazy Horse]/03 - Round & Round (It Won't Be Long).mp3"
cp -t ./ "/media/Music/Audio/Classics/Neil Young/Everybody Knows This Is Nowhere [Crazy Horse]/04 - Down by the River.mp3"
cp -t ./ "/media/Music/Audio/Classics/Neil Young/Everybody Knows This Is Nowhere [Crazy Horse]/06 - Running Dry (Requiem for the Rockets).mp3"
cp -t ./ "/media/Music/Audio/Classics/Neil Young/Cowgirl in the Sand.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/Neko Case - The Worse Things Get The Harder I Fight The Harder I Fight The More I Love You/01 Wild Creatures.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/Neko Case - The Worse Things Get The Harder I Fight The Harder I Fight The More I Love You/05 Bracing For Sunday.mp3"
cp -t ./ "/media/Music/Audio/Nickelback/[2005] All The Right Reasons/03 - Photograph.mp3"
cp -t ./ "/media/Music/Audio/Nickelback/[2005] All The Right Reasons/04 - Animals.mp3"
cp -t ./ "/media/Music/Audio/Nickelback/[2005] All The Right Reasons/05 - Savin Me.mp3"
cp -t ./ "/media/Music/Audio/Nickelback/[2005] All The Right Reasons/07 - Next Contestant.mp3"
cp -t ./ "/media/Music/Audio/Nickelback/[2005] All The Right Reasons/10 - Someone That Youre With.mp3"
cp -t ./ "/media/Music/Audio/Nickelback/[2005] All The Right Reasons/11 - Rockstar.mp3"
cp -t ./ "/media/Music/Audio/Nickelback/[2008] Dark Horse/01 - Something In Your Mouth.mp3"
cp -t ./ "/media/Music/Audio/Nickelback/[2008] Dark Horse/04 - I'd Come For You.mp3"
cp -t ./ "/media/Music/Audio/Nickelback/[2008] Dark Horse/07 - Never Gonna Be Alone.mp3"
cp -t ./ "/media/Music/Audio/Nickelback/[2008] Dark Horse/08 - Shakin' Hands.mp3"
cp -t ./ "/media/Music/Audio/Nickelback/[2011] Here And Now/06 - Lullaby.mp3"
cp -t ./ "/media/Music/Audio/Nickelback/[2011] Here And Now/09 - Holding On To Heaven.mp3"
cp -t ./ "/media/Music/Audio/Nickelback/[2001] Silver Side Up/02 - How You Remind Me.mp3"
cp -t ./ "/media/Music/Audio/Nirvana/Bleach/05-Love Buzz.mp3"
cp -t ./ "/media/Music/Audio/Nirvana/Bleach/07-Negative Creep.mp3"
cp -t ./ "/media/Music/Audio/Nirvana/In Utero/03-Heart-Shaped Box.mp3"
cp -t ./ "/media/Music/Audio/Nirvana/In Utero/04-Rape Me.mp3"
cp -t ./ "/media/Music/Audio/Nirvana/In Utero/12-All Apologies.mp3"
cp -t ./ "/media/Music/Audio/Nirvana/The Man Who Sold the World.mp3"
cp -t ./ "/media/Music/Audio/Nirvana/Where Did You Sleep Last Night.mp3"
cp -t ./ "/media/Music/Audio/Nirvana/Nevermind/01-Smells Like Teen Spirit.mp3"
cp -t ./ "/media/Music/Audio/Nirvana/Nevermind/02-In Bloom.mp3"
cp -t ./ "/media/Music/Audio/Nirvana/Nevermind/03-Come As You Are.mp3"
cp -t ./ "/media/Music/Audio/Nirvana/Nevermind/05-Lithium.mp3"
cp -t ./ "/media/Music/Audio/Nirvana/Nevermind/07-Territorial Pissings.mp3"
cp -t ./ "/media/Music/Audio/Nirvana/Nevermind/08-Drain You.mp3"
cp -t ./ "/media/Music/Audio/Nirvana/Nevermind/12-Something In The Way.mp3"
cp -t ./ "/media/Music/Audio/Nirvana/You Know You're Right.mp3"
cp -t ./ "/media/Music/Audio/Norah Jones/Non Album Tracks/06 Where Have All The Flowers Gone.mp3"
cp -t ./ "/media/Music/Audio/Norah Jones/09 The Fall (2009)/01 The Fall (2009)/12 Tell Yer Mama.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/Damnation (2003)/02 - In My Time of Need.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Ten Million Slaves.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Hey Joe.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Ozzy/Black Rain/07-Civilize The Universe.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Ozzy/Revelation(Mother earth).MP3"
cp -t ./ "/media/Music/Audio/Metal stuff/Ozzy/Mama,I'm coming home.MP3"
cp -t ./ "/media/Music/Audio/Metal stuff/Ozzy/No more tears.MP3"
cp -t ./ "/media/Music/Audio/Metal stuff/Ozzy/Fire In The Sky.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Ozzy/No More Tears [Edit].mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Ozzy/The Ultimate Sin/04-Thank God For The Bomb.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Ozzy/In My Life.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Ozzy/Sympathy For The Devil.mp3"
cp -t ./ "/media/Music/Audio/Pantera/Cowboys From Hell/01 - Cowboys From Hell.mp3"
cp -t ./ "/media/Music/Audio/Pantera/Cowboys From Hell/05 - Cemetery Gates.mp3"
cp -t ./ "/media/Music/Audio/Punk/Horses/01 Gloria.mp3"
cp -t ./ "/media/Music/Audio/Pearl Jam/Backspacer (2009)/03 - The Fixer.mp3"
cp -t ./ "/media/Music/Audio/Pearl Jam/Backspacer (2009)/04 - Johnny Guitar.mp3"
cp -t ./ "/media/Music/Audio/Pearl Jam/Backspacer (2009)/06 - Amongst The Waves.mp3"
cp -t ./ "/media/Music/Audio/Pearl Jam/Backspacer (2009)/07 - Unthought Known.mp3"
cp -t ./ "/media/Music/Audio/Pearl Jam/Backspacer (2009)/09 - Speed Of Sound.mp3"
cp -t ./ "/media/Music/Audio/Pearl Jam/Off He Goes.mp3"
cp -t ./ "/media/Music/Audio/Pearl Jam/01 Ten/01 - Once.mp3"
cp -t ./ "/media/Music/Audio/Pearl Jam/01 Ten/02 - Even flow.mp3"
cp -t ./ "/media/Music/Audio/Pearl Jam/01 Ten/06 - Jeremy.mp3"
cp -t ./ "/media/Music/Audio/Pearl Jam/01 Ten/09- Garden.mp3"
cp -t ./ "/media/Music/Audio/Pearl Jam/01 Ten/11 - Release.mp3"
cp -t ./ "/media/Music/Audio/Pearl Jam/01 Ten/14 - Dirty Frank.mp3"
cp -t ./ "/media/Music/Audio/Pearl Jam/01 Ten/03 - Alive.mp3"
cp -t ./ "/media/Music/Audio/Pearl Jam/Better Man.mp3"
cp -t ./ "/media/Music/Audio/Pearl Jam/02 Vs (1993)/03-Daughter.mp3"
cp -t ./ "/media/Music/Audio/Pearl Jam/02 Vs (1993)/05-Dissident.mp3"
cp -t ./ "/media/Music/Audio/Classics/Another Brick in the Wall.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/Carnival of Rust/01 - Fire.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/Carnival of Rust/02 - Sorry go 'round.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/Carnival of Rust/03 - Carnival Of Rust.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/Carnival of Rust/05 - Gravity.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/Carnival of Rust/08 - Desire.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Zakk Wylde/Cry Me A River.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/Purple Rain.mp3"
cp -t ./ "/media/Music/Audio/Queen/Classic Queen/07 Radio Ga Ga.mp3"
cp -t ./ "/media/Music/Audio/Queen/Classic Queen/09 I Want It All.mp3"
cp -t ./ "/media/Music/Audio/Queen/Greatest Hits III/Under Pressure (With David Bowie).mp3"
cp -t ./ "/media/Music/Audio/Queen/Greatest Hits III/Another One Bites The Dust (With Wyclef Jean).mp3"
cp -t ./ "/media/Music/Audio/R.E.M/1992 Automatic For The People/01 Drive.mp3"
cp -t ./ "/media/Music/Audio/R.E.M/1992 Automatic For The People/02 Try Not To Breathe.mp3"
cp -t ./ "/media/Music/Audio/R.E.M/1992 Automatic For The People/03 The Sidewinder Sleeps Tonite.mp3"
cp -t ./ "/media/Music/Audio/R.E.M/1992 Automatic For The People/04 Everybody Hurts.mp3"
cp -t ./ "/media/Music/Audio/R.E.M/1992 Automatic For The People/08 Ignoreland.mp3"
cp -t ./ "/media/Music/Audio/R.E.M/1992 Automatic For The People/10 Man On The Moon.mp3"
cp -t ./ "/media/Music/Audio/R.E.M/1992 Automatic For The People/11 Nightswimming.mp3"
cp -t ./ "/media/Music/Audio/R.E.M/1991 Out Of Time/02 Losing My Religion.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/Creep.mp3"
cp -t ./ "/media/Music/Audio/Rage Against the Machine/Evil Empire [1996]/02-Bulls On Parade.mp3"
cp -t ./ "/media/Music/Audio/Rage Against the Machine/Rage Against The Machine [1992]/01 - Bombtrack.mp3"
cp -t ./ "/media/Music/Audio/Rage Against the Machine/Rage Against The Machine [1992]/02 - Killing in the name.mp3"
cp -t ./ "/media/Music/Audio/Rage Against the Machine/Rage Against The Machine [1992]/05 - Bullet In The Head.mp3"
cp -t ./ "/media/Music/Audio/Rage Against the Machine/Rage Against The Machine [1992]/07 - Wake Up.mp3"
cp -t ./ "/media/Music/Audio/Rage Against the Machine/The Battle Of Los Angeles [1999]/02-Guerilla Radio.mp3"
cp -t ./ "/media/Music/Audio/Rage Against the Machine/The Battle Of Los Angeles [1999]/03-Calm like a bomb.mp3"
cp -t ./ "/media/Music/Audio/Rage Against the Machine/The Battle Of Los Angeles [1999]/04-Mic Check.mp3"
cp -t ./ "/media/Music/Audio/Classics/Rainbow/Stargazer.mp3"
cp -t ./ "/media/Music/Audio/Classics/Rainbow/A Light In The Black.mp3"
cp -t ./ "/media/Music/Audio/Classics/Rainbow/The Temple Of The King.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/Umbrella.mp3"
cp -t ./ "/media/Music/Audio/Post Led Zep/Band of Joy (2010)/03 Cindy I_ll Marry You One Day.mp3"
cp -t ./ "/media/Music/Audio/Post Led Zep/Raising Sand/08 Trampled Rose.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/Smooth Operator.mp3"
cp -t ./ "/media/Music/Audio/Misc Artists/Sean Paul/Like Glue.mp3"
cp -t ./ "/media/Music/Audio/Misc Artists/Sean Paul/We Be Burnin.mp3"
cp -t ./ "/media/Music/Audio/Misc Artists/Sean Paul/Give It Up To Me.mp3"
cp -t ./ "/media/Music/Audio/Senses Fail/From The Depths Of Dreams/06 - One Eight Seven.mp3"
cp -t ./ "/media/Music/Audio/Senses Fail/Let It Enfold You/04-Buried a Lie.mp3"
cp -t ./ "/media/Music/Audio/Senses Fail/Let It Enfold You/06-Rum Is for Drinking, Not for Burning.mp3"
cp -t ./ "/media/Music/Audio/Senses Fail/Still Searching/01 - The Rapture.mp3"
cp -t ./ "/media/Music/Audio/Senses Fail/Still Searching/03 - Sick or sane.mp3"
cp -t ./ "/media/Music/Audio/Senses Fail/Still Searching/04 - Can't Be Saved.mp3"
cp -t ./ "/media/Music/Audio/Senses Fail/Still Searching/05 - Calling All Cars.mp3"
cp -t ./ "/media/Music/Audio/Senses Fail/Still Searching/07 - Still Searching.mp3"
cp -t ./ "/media/Music/Audio/Senses Fail/Still Searching/09 - Lost And Found.mp3"
cp -t ./ "/media/Music/Audio/Senses Fail/Still Searching/13 - The Priest And The Matador.mp3"
cp -t ./ "/media/Music/Audio/Senses Fail/Still Searching/Can't Be Saved (Acoustic).mp3"
cp -t ./ "/media/Music/Audio/Senses Fail/Still Searching/Lost and Found (Acoustic).mp3"
cp -t ./ "/media/Music/Audio/Senses Fail/Still Searching/17 - Mason's Revenge.mp3"
cp -t ./ "/media/Music/Audio/Senses Fail/Still Searching/19 - Salvation.mp3"
cp -t ./ "/media/Music/Audio/Senses Fail/The Fire (2010)/08 Lifeboats.mp3"
cp -t ./ "/media/Music/Audio/Classics/Simon & Garfunkel/Bridge Over Troubled Waters.mp3"
cp -t ./ "/media/Music/Audio/Classics/Simon & Garfunkel/Mrs. Robinson.mp3"
cp -t ./ "/media/Music/Audio/Classics/Simon & Garfunkel/I Am A Rock (2).mp3"
cp -t ./ "/media/Music/Audio/Classics/Simon & Garfunkel/Me and Julio Down By the School Yard.mp3"
cp -t ./ "/media/Music/Audio/Classics/Simon & Garfunkel/Still crazy after all these years.mp3"
cp -t ./ "/media/Music/Audio/Classics/Simon & Garfunkel/Keep The Customer Satisfied.mp3"
cp -t ./ "/media/Music/Audio/Classics/Simon & Garfunkel/Dust In The Wind.mp3"
cp -t ./ "/media/Music/Audio/Classics/Simon & Garfunkel/I Am A Rock.mp3"
cp -t ./ "/media/Music/Audio/Classics/Simon & Garfunkel/The lion sleeps tonight.mp3"
cp -t ./ "/media/Music/Audio/Classics/Simon & Garfunkel/Cats in The Cradle.mp3"
cp -t ./ "/media/Music/Audio/Slash/R & FN'R/02-Crucify the Dead.mp3"
cp -t ./ "/media/Music/Audio/Classics/needles and pins.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/AlmostFamous/America.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/AlmostFamous/It Wouldn't Have Made Any Difference.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/AlmostFamous/Fever Dog.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/AlmostFamous/Slip Away.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/AlmostFamous/Something In The Air.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/You've Got To Hide Your Love Away (Beatles).mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/Outside.mp3"
cp -t ./ "/media/Music/Audio/Jefferson/Starship - Greatest Hits/02 - Find Your Way Back.MP3"
cp -t ./ "/media/Music/Audio/Jefferson/Starship - Greatest Hits/06 - Don't Lose Any Sleep.MP3"
cp -t ./ "/media/Music/Audio/Jefferson/Starship - Greatest Hits/07 - We Built This City.MP3"
cp -t ./ "/media/Music/Audio/Jefferson/Starship - Greatest Hits/09 - Nothing's Gonna Stop Us Now.MP3"
cp -t ./ "/media/Music/Audio/00NewStuffs/Indro/New/Texas Flood.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Couldn't Stand The Weather (1984)/01 - Scuttle Buttin'.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Couldn't Stand The Weather (1984)/02 - Couldn't Stand The Weather.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Couldn't Stand The Weather (1984)/04 - Voodoo Chile (Slight Return).mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Couldn't Stand The Weather (1984)/06 - Tin Pan Alley (aka Roughest Place in Town).mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./Couldn't Stand The Weather (1984)/13 - Come On (Pt.III).mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/Core/07 Creep.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/Core/09 Plush.mp3"
cp -t ./ "/media/Music/Audio/Misc Albums/Core/12 Where the River Goes.mp3"
cp -t ./ "/media/Music/Audio/Story of the Year/In wake of determination/01-We Don't Care Anymore.mp3"
cp -t ./ "/media/Music/Audio/Story of the Year/In wake of determination/03-Our Time Is Now.mp3"
cp -t ./ "/media/Music/Audio/Story of the Year/In wake of determination/05-Stereo.mp3"
cp -t ./ "/media/Music/Audio/Story of the Year/In wake of determination/06-Five Against The World.mp3"
cp -t ./ "/media/Music/Audio/Story of the Year/In wake of determination/07-Sleep.mp3"
cp -t ./ "/media/Music/Audio/Story of the Year/Page Avenue (2003)/until the day i die (acoustic).mp3"
cp -t ./ "/media/Music/Audio/Story of the Year/Page Avenue (2003)/01 - And the Hero Will Drown.mp3"
cp -t ./ "/media/Music/Audio/Story of the Year/Page Avenue (2003)/02 - Until the Day I Die.mp3"
cp -t ./ "/media/Music/Audio/Story of the Year/Page Avenue (2003)/03 - Anthem of Our Dying Day.mp3"
cp -t ./ "/media/Music/Audio/Story of the Year/Page Avenue (2003)/04 - In the Shadows.mp3"
cp -t ./ "/media/Music/Audio/Story of the Year/Page Avenue (2003)/07 - Burning Years.mp3"
cp -t ./ "/media/Music/Audio/Story of the Year/The Black Swan/04 Tell Me (Pac).mp3"
cp -t ./ "/media/Music/Audio/Crap/Sum 41/Screaming Bloody Murder [2011]/02-Screaming Bloody Murder.mp3"
cp -t ./ "/media/Music/Audio/Crap/Sum 41/Underclass Hero/01Underclass Hero.mp3"
cp -t ./ "/media/Music/Audio/Crap/Sum 41/Underclass Hero/02Walking Disaster.mp3"
cp -t ./ "/media/Music/Audio/Crap/Sum 41/Underclass Hero/07March of the Dogs.mp3"
cp -t ./ "/media/Music/Audio/Crap/Sum 41/Underclass Hero/09With Me.mp3"
cp -t ./ "/media/Music/Audio/Crap/Sum 41/Underclass Hero/10Pull the Curtain.mp3"
cp -t ./ "/media/Music/Audio/Crap/Sum 41/Underclass Hero/12Best of Me.mp3"
cp -t ./ "/media/Music/Audio/Crap/Sum 41/Underclass Hero/13Confusing and frustrating.mp3"
cp -t ./ "/media/Music/Audio/Crap/Sum 41/Underclass Hero/14So long goodbye.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/Eye of the Tiger (Rocky Theme).mp3"
cp -t ./ "/media/Music/Audio/Crap/System Of A Down/Hypnotize/04 - Hypnotize.mp3"
"#EXTINF:249,System Of A Down - Radio/Video"
cp -t ./ "/media/Music/Audio/Crap/System Of A Down/Mezmerize/Radio-Video.mp3"
cp -t ./ "/media/Music/Audio/Crap/System Of A Down/Toxicity/12 Toxicity.mp3"
cp -t ./ "/media/Music/Audio/Crap/System Of A Down/Toxicity/13 Psycho.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./The Allman Brothers Band/At Fillmore East (1971)/204-Drunken Hearted Boy.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./The Allman Brothers Band/Brothers And Sisters (1973)/02-Ramblin' Man.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./The Allman Brothers Band/Brothers And Sisters (1973)/06-Jessica.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./The Allman Brothers Band/Eat A Peach (1972)/05-One Way Out.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./The Allman Brothers Band/Hittin' The Note (2003)/02-High Cost Of Low Living.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./The Allman Brothers Band/Hittin' The Note (2003)/03-Desdemona.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./The Allman Brothers Band/Hittin' The Note (2003)/04-Woman Across The River.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./The Allman Brothers Band/Hittin' The Note (2003)/05-Old Before My Time.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./The Allman Brothers Band/Hittin' The Note (2003)/07-Maydelle.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./The Allman Brothers Band/Hittin' The Note (2003)/08-Rockin' Horse.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./The Allman Brothers Band/Hittin' The Note (2003)/09-Heart Of Stone.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./The Allman Brothers Band/The Allman Brothers Band (1969)/02-It's Not My Cross To Bear.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./The Allman Brothers Band/The Allman Brothers Band (1969)/07-Whipping Post.mp3"
cp -t ./ "/media/Music/Audio/Blues, Southern, etc./The Allman Brothers Band/Where It All Begins (1994)/04-Soulshine.mp3"
cp -t ./ "/media/Music/Audio/Classics/I shall be released.mp3"
cp -t ./ "/media/Music/Audio/The Beatles/The Beatles [2009] Greatest Hits [Remastered]/09 And I Love Her.mp3"
cp -t ./ "/media/Music/Audio/The Beatles/The Beatles [2009] Greatest Hits [Remastered]/14 Can't Buy Me Love.mp3"
cp -t ./ "/media/Music/Audio/The Beatles/The Beatles [2009] Greatest Hits [Remastered]/16 Here Comes The Sun.mp3"
cp -t ./ "/media/Music/Audio/The Beatles/The Beatles [2009] Greatest Hits [Remastered]/35 Don't Let Me Down.mp3"
cp -t ./ "/media/Music/Audio/The Beatles/Revolver [Stereo Remaster 2009]/01. Taxman.mp3"
cp -t ./ "/media/Music/Audio/The Beatles/Revolver [Stereo Remaster 2009]/09. And Your Bird Can Sing.mp3"
cp -t ./ "/media/Music/Audio/The Beatles/Rubber Soul (Remastered)2009/03-You Wont See Me.mp3"
cp -t ./ "/media/Music/Audio/The Beatles/Rubber Soul (Remastered)2009/11-In My Life.mp3"
cp -t ./ "/media/Music/Audio/The Beatles/The Beatles [2009] Greatest Hits [Remastered]/30 While My Guitar Gently Weeps.mp3"
cp -t ./ "/media/Music/Audio/The Beatles/Hey jude.mp3"
cp -t ./ "/media/Music/Audio/The Black Keys/2008 - Attack & Release/04 Psychotic Girl.mp3"
cp -t ./ "/media/Music/Audio/The Black Keys/Brothers/07-The Only One.mp3"
cp -t ./ "/media/Music/Audio/The Black Keys/Brothers/10-Sinister Kid.mp3"
cp -t ./ "/media/Music/Audio/The Black Keys/Brothers/14-Never Give You Up.mp3"
cp -t ./ "/media/Music/Audio/The Black Keys/Brothers/15-These Days.mp3"
cp -t ./ "/media/Music/Audio/The Black Keys/2012 El Camino/El Camino/01 - Lonely Boy.mp3"
cp -t ./ "/media/Music/Audio/Punk/The Clash/London Calling/01 - London Calling.mp3"
cp -t ./ "/media/Music/Audio/Punk/The Clash/London Calling/03 - Jimmy Jazz.mp3"
cp -t ./ "/media/Music/Audio/Punk/The Clash/The Clash/The Clash - 01 Janie Jones.mp3"
cp -t ./ "/media/Music/Audio/Punk/The Clash/The Clash/The Clash - 08 London's Bur.mp3"
cp -t ./ "/media/Music/Audio/Punk/The Clash/04-the_clash-i_fought_the_law.mp3"
cp -t ./ "/media/Music/Audio/Misc Artists/The Cranberries/2003 - Stars (The Best of Cranberries 1992 - 2002)/02-The Cranberries-Linger.mp3"
cp -t ./ "/media/Music/Audio/Misc Artists/The Cranberries/2003 - Stars (The Best of Cranberries 1992 - 2002)/03-The Cranberries-Zombie.mp3"
cp -t ./ "/media/Music/Audio/Misc Artists/The Cranberries/2003 - Stars (The Best of Cranberries 1992 - 2002)/04-The Cranberries-Ode to My Family.mp3"
cp -t ./ "/media/Music/Audio/Misc Artists/The Cranberries/2003 - Stars (The Best of Cranberries 1992 - 2002)/18-The Cranberries-Daffodil Lament [ ].mp3"
cp -t ./ "/media/Music/Audio/Misc Artists/The Cranberries/When youre gone.mp3"
cp -t ./ "/media/Music/Audio/The Doors/When The Music''s Over.mp3"
cp -t ./ "/media/Music/Audio/The Doors/In Concert/01 Roadhouse blues.mp3"
cp -t ./ "/media/Music/Audio/The Doors/In Concert/03 Light my fire.mp3"
cp -t ./ "/media/Music/Audio/The Doors/L.A.Woman/05 L.A. Woman.mp3"
cp -t ./ "/media/Music/Audio/The Doors/L.A.Woman/07 Hyacinth House.mp3"
cp -t ./ "/media/Music/Audio/The Doors/L.A.Woman/10 Riders On The Storm.mp3"
cp -t ./ "/media/Music/Audio/The Doors/Morrison Hotel/01 Roadhouse Blues.mp3"
cp -t ./ "/media/Music/Audio/The Doors/Morrison Hotel/10 Indian Summer.mp3"
cp -t ./ "/media/Music/Audio/The Doors/The Doors/01 Break on Through (to the Other Si.mp3"
cp -t ./ "/media/Music/Audio/The Doors/The Doors/06 Light My Fire.mp3"
cp -t ./ "/media/Music/Audio/The Doors/The Doors/12 When The Music's Over.mp3"
cp -t ./ "/media/Music/Audio/The Doors/The Celebration Of The Lizard.mp3"
cp -t ./ "/media/Music/Audio/The Doors/Without A Safety Net/03 - Hyacinth House.mp3"
cp -t ./ "/media/Music/Audio/Classics/American Woman.mp3"
cp -t ./ "/media/Music/Audio/Punk/Misfits/Cuts From The Crypt/11-1,000,000 Years BC.mp3"
cp -t ./ "/media/Music/Audio/Norah Jones/03 The Peter Malick Group (feat. Norah Jones) - New York City (2003)/03-Deceptively Yours.mp3"
cp -t ./ "/media/Music/Audio/Jack White/The Raconteurs/Broken Boy Soldiers/01 - Steady As She Goes.mp3"
cp -t ./ "/media/Music/Audio/Jack White/The Raconteurs/Broken Boy Soldiers/03 - Broken Boy Soldier.mp3"
cp -t ./ "/media/Music/Audio/Punk/The Best Of The Ramones/01 Pet Semetary.mp3"
cp -t ./ "/media/Music/Audio/Punk/The Best Of The Ramones/12 Surfin' Bird.mp3"
cp -t ./ "/media/Music/Audio/Punk/The Best Of The Ramones/04 Poison Heart.mp3"
cp -t ./ "/media/Music/Audio/Punk/The Best Of The Ramones/Blitzkrieg Bop.mp3"
cp -t ./ "/media/Music/Audio/The Rolling Stones/Goin' Home.mp3"
cp -t ./ "/media/Music/Audio/The Rolling Stones/Exile On Main Street/109 Loving Cup.mp3"
cp -t ./ "/media/Music/Audio/The Rolling Stones/Exile On Main Street/202 Plundered My Soul.mp3"
cp -t ./ "/media/Music/Audio/The Rolling Stones/Don't Stop.mp3"
cp -t ./ "/media/Music/Audio/The Rolling Stones/Till The Next Goodbye.mp3"
cp -t ./ "/media/Music/Audio/The Rolling Stones/Disc 1/21.You Can't Always Get What You Want.mp3"
cp -t ./ "/media/Music/Audio/The Rolling Stones/Disc 1/22.Sympathy For The Devil.mp3"
cp -t ./ "/media/Music/Audio/The Rolling Stones/Disc 2/07.Wild Horses.mp3"
"#EXTINF:156,The Sex Pistols - Johnny B. Goode/Road Runner"
cp -t ./ "/media/Music/Audio/Punk/Sex Pistols/The Great Rock 'N' Roll Swindle/03. Johnny B Goode.mp3"
cp -t ./ "/media/Music/Audio/Smashing Pumpkins/[1998] Adore/07. Crestfallen.mp3"
cp -t ./ "/media/Music/Audio/Smashing Pumpkins/[1998] Adore/14. For Martha.mp3"
cp -t ./ "/media/Music/Audio/Smashing Pumpkins/Gish (1991)/04-Bury Me.mp3"
cp -t ./ "/media/Music/Audio/Smashing Pumpkins/Gish (1991)/06-Suffer.mp3"
cp -t ./ "/media/Music/Audio/Smashing Pumpkins/Rotten Apples/102 - Rhinoceros (1991).mp3"
cp -t ./ "/media/Music/Audio/Smashing Pumpkins/Rotten Apples/114 - Everlasting Gaze (2000).mp3"
cp -t ./ "/media/Music/Audio/Smashing Pumpkins/The Smashing Pumpkins - Oceania - 2012/07 - Pinwheels.mp3"
cp -t ./ "/media/Music/Audio/Smashing Pumpkins/[2007] Zietgeist/04. That's The Way (My Love Is).mp3"
cp -t ./ "/media/Music/Audio/The Used/Artwork/03 Born to Quit.mp3"
cp -t ./ "/media/Music/Audio/The Used/Artwork/04 Kissing You Goodbye.mp3"
cp -t ./ "/media/Music/Audio/The Used/In Love And Death (2005)/13 - Under Pressure (Queen Cover).mp3"
cp -t ./ "/media/Music/Audio/The Used/Lies For The Liars/01-The Ripper.mp3"
cp -t ./ "/media/Music/Audio/The Used/Lies For The Liars/03-The Bird and the Worm.mp3"
cp -t ./ "/media/Music/Audio/The Used/Lies For The Liars/04-Earthquake.mp3"
cp -t ./ "/media/Music/Audio/The Used/Lies For The Liars/05-Hospital.mp3"
cp -t ./ "/media/Music/Audio/The Used/Lies For The Liars/10-Liar Liar (Burn In Hell).mp3"
cp -t ./ "/media/Music/Audio/The Used/Shallow Believer(2008)/10-Tunnel.mp3"
cp -t ./ "/media/Music/Audio/The Velvet Underground/The Velvet Underground & Nico/04 Venus In Furs.mp3"
cp -t ./ "/media/Music/Audio/The Velvet Underground/The Velvet Underground & Nico/06 All Tomorrow's Parties.mp3"
cp -t ./ "/media/Music/Audio/The Velvet Underground/The Velvet Underground & Nico/07 Heroin.mp3"
cp -t ./ "/media/Music/Audio/Jack White/The White Stripes/2000 - De Stijl/01 - You're Pretty Good Looking (For a Girl).mp3"
cp -t ./ "/media/Music/Audio/Jack White/The White Stripes/2000 - De Stijl/04 - Apple Blossom.mp3"
cp -t ./ "/media/Music/Audio/Jack White/The White Stripes/2000 - De Stijl/08 - Truth Doesn't Make a Noise.mp3"
cp -t ./ "/media/Music/Audio/Jack White/The White Stripes/2007 - Icky Thump/02 - You Don't Know What Love Is (You Just Do As You're Told).mp3"
cp -t ./ "/media/Music/Audio/Jack White/The White Stripes/2007 - Icky Thump/06 - Prickly Thorn, But Sweetly Worn.mp3"
cp -t ./ "/media/Music/Audio/Jack White/The White Stripes/2007 - Icky Thump/09 - Rag And Bone.mp3"
cp -t ./ "/media/Music/Audio/Jack White/The White Stripes/2001 - White Blood Cells/02 - Hotel Yorba.mp3"
cp -t ./ "/media/Music/Audio/Jack White/The White Stripes/2001 - White Blood Cells/06 - Little Room.mp3"
cp -t ./ "/media/Music/Audio/Jack White/The White Stripes/2001 - White Blood Cells/09 - We're Going to Be Friends.mp3"
cp -t ./ "/media/Music/Audio/Classics/Behind Blue Eyes.mp3"
cp -t ./ "/media/Music/Audio/Classics/The Yardbirds/Heart Full Of Soul (Sitar Version).mp3"
cp -t ./ "/media/Music/Audio/Crap/Theory of a Deadman - Scars and Souvenirs (2008)/04 - Not Meant to Be.mp3"
cp -t ./ "/media/Music/Audio/Crap/Theory of a Deadman - Scars and Souvenirs (2008)/07 - Heaven (Little by Little).mp3"
cp -t ./ "/media/Music/Audio/Crap/Theory of a Deadman - Scars and Souvenirs (2008)/08 - Bad Girlfriend.mp3"
cp -t ./ "/media/Music/Audio/Crap/Theory of a Deadman - Scars and Souvenirs (2008)/09 - Hate My Life.mp3"
cp -t ./ "/media/Music/Audio/Crap/Theory of a Deadman - Scars and Souvenirs (2008)/11 - End of the Summer.mp3"
cp -t ./ "/media/Music/Audio/Crap/Theory of a Deadman - Scars and Souvenirs (2008)/12 - Wait for Me.mp3"
cp -t ./ "/media/Music/Audio/Classics/Whisky in the jar.mp3"
cp -t ./ "/media/Music/Audio/Tom Petty/Damn The Torpedoes [2010]/101-Refugee.mp3"
cp -t ./ "/media/Music/Audio/Tom Petty/Damn The Torpedoes [2010]/103-Even The Losers.mp3"
cp -t ./ "/media/Music/Audio/Tom Petty/Damn The Torpedoes [2010]/104-Shadow Of A Doubt (a Complex Kid).mp3"
cp -t ./ "/media/Music/Audio/Tom Petty/Damn The Torpedoes [2010]/109-Louisiana Rain.mp3"
cp -t ./ "/media/Music/Audio/Tom Petty/Damn The Torpedoes [2010]/205-Shadow Of A Doubt (a Complex Kid) (live).mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/Where The Streets Have No Name.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/I Still Haven't Found What I'm Looking For.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/With or Without You.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Misc/Serenade.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/You Keep Me Hanging On.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/Magic Carpet Ride.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/Spooky.mp3"
cp -t ./ "/media/Music/Audio/Classics/Nuggets - Original Artyfacts from the First Psychedelic Era, 1965-1968/CD 1/06 A Public Execution.mp3"
cp -t ./ "/media/Music/Audio/Classics/Nuggets - Original Artyfacts from the First Psychedelic Era, 1965-1968/CD 2/30 (We Ain't Got) Nothin' Yet.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./O Brother, Where Art Thou/04 - Down To The River To Pray.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./O Brother, Where Art Thou/05 - I Am A Man Of Constant Sorrow (Radio Station Version).mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./O Brother, Where Art Thou/09 - I'll Fly Away.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./O Brother, Where Art Thou/14 - O Death.mp3"
cp -t ./ "/media/Music/Audio/Country, Folk, etc./O Brother, Where Art Thou/16 - I Am A Man Of Constant Sorrow.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/Im A Man.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/The Best Heavy Metal Album Ever/Ace Of Spades.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/The Best Heavy Metal Album Ever/Talk Dirty To Me.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/Danger Zone.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/its been a while.mp3"
cp -t ./ "/media/Music/Audio/Slash/Velvet Revolver/You Got No Right.mp3"
cp -t ./ "/media/Music/Audio/Misc Songs/Ratfinks, Suicide Tanks and Cannibal Girls.mp3"
cp -t ./ "/media/Music/Audio/Wolfmother/Wolfmother/05 - Mind's Eye.mp3"
cp -t ./ "/media/Music/Audio/Punk/Pop_Alt_etc/Ocean avenue.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Zakk Wylde/Book Of Shadows/03 - Road Back Home.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Zakk Wylde/Book Of Shadows/07 - Dead As Yesterday.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Zakk Wylde/Book Of Shadows/14 - Peddlers Of Death.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Zakk Wylde/Candle In The Wind.mp3"
cp -t ./ "/media/Music/Audio/Metal stuff/Zakk Wylde/Going To California.mp3"
